# Generated by Django 3.0.7 on 2020-06-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '2. Enrolled',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '1. Students',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('enrolled', models.ManyToManyField(related_name='years', to='students.Enrolled')),
            ],
            options={
                'verbose_name_plural': '4. Years',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=64)),
                ('years', models.ManyToManyField(related_name='semesters', to='students.Year')),
            ],
            options={
                'verbose_name_plural': '5. Semesters',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=64)),
                ('enrolled', models.ManyToManyField(related_name='majors', to='students.Enrolled')),
            ],
            options={
                'verbose_name_plural': '3. Majors',
            },
        ),
        migrations.AddField(
            model_name='enrolled',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='students.Student'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('semesters', models.ManyToManyField(related_name='courses', to='students.Semester')),
            ],
            options={
                'verbose_name_plural': '6. Courses',
            },
        ),
    ]
