# Generated by Django 3.0.7 on 2020-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='moo', max_length=64),
            preserve_default=False,
        ),
    ]
