# Generated by Django 3.0.7 on 2020-07-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_aptranfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=64)),
                ('score', models.IntegerField()),
                ('years', models.ManyToManyField(related_name='ap', to='students.Year')),
            ],
            options={
                'verbose_name_plural': '7. AP',
            },
        ),
        migrations.DeleteModel(
            name='APTranfer',
        ),
    ]
