# Generated by Django 3.0.7 on 2020-07-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200722_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ap',
            options={'verbose_name_plural': '7. Course AP'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '6. Course Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrolled',
            options={'verbose_name_plural': '2. Course Enrolled'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name_plural': '3. Course Majors'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': '5. Course Semesters'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '1. Course Students'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name_plural': '4. Course Years'},
        ),
    ]
