# Generated by Django 3.0.7 on 2020-07-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200723_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ap',
            options={'verbose_name_plural': '7. Helper AP'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '6. Helper Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrolled',
            options={'verbose_name_plural': '2. Helper Enrolled'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name_plural': '3. Helper Majors'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': '5. Helper Semesters'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '1. Helper Students'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name_plural': '4. Helper Years'},
        ),
    ]
