# Generated by Django 3.0.7 on 2020-06-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='creditrange',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requirements',
            name='numcoursesneeded',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='courseoptions',
            name='credithour',
            field=models.IntegerField(default=1),
        ),
    ]
