# Generated by Django 3.0.7 on 2020-06-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200624_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='courses.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('credithour', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereq', models.CharField(max_length=64)),
                ('course', models.ManyToManyField(blank=True, related_name='prereqs', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=64)),
                ('creditrange', models.IntegerField(default=1)),
                ('numcoursesneeded', models.IntegerField(default=1)),
                ('category', models.ManyToManyField(related_name='requirements', to='courses.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseoptions',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='prerequisites',
            name='course',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='CourseOptions',
        ),
        migrations.DeleteModel(
            name='Prerequisites',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
        migrations.AddField(
            model_name='course',
            name='requirement',
            field=models.ManyToManyField(related_name='courses', to='courses.Requirement'),
        ),
    ]
