# Generated by Django 3.0.7 on 2020-06-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200624_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='requirement',
            new_name='requirements',
        ),
        migrations.RenameField(
            model_name='prereq',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='category',
            new_name='categories',
        ),
    ]
