# Generated by Django 3.0.7 on 2020-07-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200723_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apcredit',
            options={'verbose_name_plural': '9. Course ApCredit'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '4. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '7. Course Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrolled',
            options={'verbose_name_plural': '2. Course Enrolled'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name_plural': '3. Course Majors'},
        ),
        migrations.AlterModelOptions(
            name='prereq',
            options={'verbose_name_plural': '8. Course Prereqs'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name_plural': '6. Course Requirements'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '1. Course Students'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '5. Course Sub Categories'},
        ),
    ]
