# Generated by Django 3.0.7 on 2020-06-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200624_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '5. Courses'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name_plural': '1. Majors'},
        ),
        migrations.AlterModelOptions(
            name='prereq',
            options={'verbose_name_plural': '6. Prereqs'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name_plural': '4. Requirements'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '3. Sub Categories'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='credithour',
            new_name='credit',
        ),
    ]
