# Generated by Django 3.0.7 on 2020-06-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200625_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='note',
            field=models.CharField(max_length=200),
        ),
    ]
