# Generated by Django 3.0.7 on 2020-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200625_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=64)),
                ('scores', models.IntegerField(default=3)),
                ('courses', models.ManyToManyField(blank=True, related_name='apcredits', to='courses.Course')),
            ],
            options={
                'verbose_name_plural': '6. ApCredit',
            },
        ),
    ]
