# Generated by Django 3.0.7 on 2020-06-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_apcredit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apcredit',
            options={'verbose_name_plural': '7. ApCredit'},
        ),
        migrations.RenameField(
            model_name='apcredit',
            old_name='scores',
            new_name='scoremax',
        ),
        migrations.AddField(
            model_name='apcredit',
            name='scoremin',
            field=models.IntegerField(default=3),
        ),
    ]
