# Generated by Django 3.0.7 on 2020-06-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200628_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
