# Generated by Django 3.0.7 on 2020-07-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200630_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='major',
            new_name='majors',
        ),
    ]
